all:string func_overloading polymorphism class_info vector class_object dynamic operator_voerflow 

string:string.cpp
	g++ -o string string.cpp

func_overloading:func_overloading.cpp
	g++ -o func_overloading func_overloading.cpp

polymorphism:polymorphism.cpp
	g++ -o polymorphism polymorphism.cpp

class_info:class_info.cpp
	g++ -o class_info class_info.cpp

vector:vector.cpp
	g++ -o vector vector.cpp

class_object:class_object.cpp
	g++ -o class_object class_object.cpp

dynamic:dynamic.cpp
	g++ -o dynamic dynamic.cpp

operator_voerflow:operator_voerflow.cpp
	g++ -o operator_voerflow operator_voerflow.cpp

clean:
	rm -rf string func_overloading polymorphism class_info vector class_object dynamic operator_voerflow 
