all:getpid shared_memory fork semaphore signal 

getpid:getpid.cpp
	g++ -o getpid getpid.cpp

shared_memory:shared_memory.cpp
	g++ -o shared_memory shared_memory.cpp

fork:fork.cpp
	g++ -o fork fork.cpp

semaphore:semaphore.cpp
	g++ -o semaphore semaphore.cpp

signal:signal.cpp
	g++ -o signal signal.cpp

clean:
	rm -rf getpid shared_memory fork semaphore signal 
