all:multi-thread_server tread_synchronization 

multi-thread_server:multi-thread_server.cpp
	g++ -o multi-thread_server multi-thread_server.cpp

tread_synchronization:tread_synchronization.cpp
	g++ -o tread_synchronization tread_synchronization.cpp

clean:
	rm -rf multi-thread_server tread_synchronization 
